version: "3"
services:
  whenyoucan-frontend:
    container_name: whenyoucan-frontend
    image: whenyoucan-frontend:latest
    restart: always
    build: .
    ports:
      - "8080:8080"
      - "3333:3000"
    volumes:
      - .:/app
      - /app/node_modules