
export const ADD_NEW_ATTENDANCE = "ADD_NEW_ATTENDANCE";

export const POST_LOGIN_FETCH = "POST_LOGIN_FETCH";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_ERROR = "POST_LOGIN_ERROR";

export const GET_AUTH_ME_FETCH = "GET_AUTH_ME_FETCH";
export const GET_AUTH_ME_SUCCESS = "GET_AUTH_ME_SUCCESS";
export const GET_AUTH_ME_ERROR = "GET_AUTH_ME_ERROR";

export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const SET_LOGGED_OUT = "SET_LOGGED_OUT";

export const DELETE_LOGOUT_FETCH = "DELETE_LOGOUT_FETCH";
export const DELETE_LOGOUT_SUCCESS = "DELETE_LOGOUT_SUCCESS";
export const DELETE_LOGOUT_ERROR = "DELETE_LOGOUT_ERROR";

export const GET_CALENDAR_FETCH = "GET_CALENDAR_FETCH";
export const GET_CALENDAR_ERROR = "GET_CALENDAR_ERROR";
export const GET_CALENDAR_SUCCESS = "GET_CALENDAR_SUCCESS";